import { writeFile } from 'node:fs/promises';
import { loadSeed } from './load-seed.mjs';

/**
 * Generates supabase/seed.sql from the TypeScript seed.
 *
 * The authored data stays the single source of truth — this script is a projection of it,
 * never a second copy to keep in sync by hand. Re-run it whenever src/data/** changes:
 *
 *   yarn db:seed-sql
 *
 * Rows are upserted rather than truncated so re-seeding a live project does not drop the
 * auth links on owners (auth_user_id is deliberately never written here — only the signup
 * trigger sets it).
 */

const lit = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  return `'${String(v).replace(/'/g, "''")}'`;
};

const arr = (values, cast) =>
  values.length ? `array[${values.map(lit).join(', ')}]::${cast}` : `array[]::${cast}`;

/** One upsert block: insert every row, and on a repeat run refresh the listed columns. */
function upsert(table, columns, rows, { conflict = 'id', update = columns.filter((c) => c !== 'id') } = {}) {
  if (rows.length === 0) return '';
  const values = rows.map((row) => `  (${columns.map((c) => row[c]).join(', ')})`).join(',\n');
  const set = update.map((c) => `${c} = excluded.${c}`).join(', ');
  return [
    `insert into public.${table} (${columns.join(', ')}) values`,
    values,
    `on conflict (${conflict}) do update set ${set};`,
    '',
  ].join('\n');
}

const { seed, remedyTable } = await loadSeed();
const remedies = Object.values(remedyTable).flat();

const sql = [
  '-- Generated by scripts/export-seed.mjs — do not edit by hand.',
  '-- Source of truth: src/data/**. Regenerate with `yarn db:seed-sql`.',
  '',
  'begin;',
  '',

  upsert('locations', ['id', 'name', 'address', 'city'],
    seed.locations.map((l) => ({ id: lit(l.id), name: lit(l.name), address: lit(l.address), city: lit(l.city) }))),

  upsert('menu_catalog', ['id', 'name', 'food_category'],
    seed.menuCatalog.map((c) => ({ id: lit(c.id), name: lit(c.name), food_category: lit(c.foodCategory) }))),

  upsert('remedies',
    ['id', 'category', 'tier', 'title', 'description', 'specific_actions', 'expected_impact', 'target_metric'],
    remedies.map((r) => ({
      id: lit(r.id),
      category: lit(r.category),
      tier: r.tier,
      title: lit(r.title),
      description: lit(r.description),
      specific_actions: arr(r.specificActions, 'text[]'),
      expected_impact: lit(r.expectedImpact),
      target_metric: lit(r.targetMetric),
    }))),

  // auth_user_id is omitted on purpose: it belongs to the signup trigger, and re-seeding
  // must not unlink an owner who has already signed in.
  upsert('owners', ['id', 'name', 'email', 'role'],
    seed.users.map((u) => ({ id: lit(u.id), name: lit(u.name), email: lit(u.email), role: lit(u.role) }))),

  upsert('restaurants', ['id', 'name', 'owner_id', 'location_id', 'cuisine', 'price_tier'],
    seed.restaurants.map((r) => ({
      id: lit(r.id),
      name: lit(r.name),
      owner_id: lit(r.ownerId),
      location_id: lit(r.locationId),
      cuisine: lit(r.cuisine),
      price_tier: r.priceTier,
    }))),

  upsert('restaurant_menu_items', ['id', 'restaurant_id', 'catalog_item_id', 'price'],
    seed.restaurantMenuItems.map((m) => ({
      id: lit(m.id),
      restaurant_id: lit(m.restaurantId),
      catalog_item_id: lit(m.catalogItemId),
      price: m.price,
    }))),

  upsert('scenarios',
    ['id', 'restaurant_id', 'target_category', 'target_catalog_item_id', 'action_date',
     'expected_outcome', 'baseline_review_ids', 'post_action_review_ids',
     'seeded_remedy_tier1_id', 'seeded_remedy_tier2_id'],
    seed.scenarios.map((s) => ({
      id: lit(s.id),
      restaurant_id: lit(s.restaurantId),
      target_category: lit(s.targetCategory),
      target_catalog_item_id: lit(s.targetCatalogItemId ?? null),
      action_date: lit(s.actionDate),
      expected_outcome: lit(s.expectedOutcome),
      baseline_review_ids: arr(s.baselineReviewIds, 'text[]'),
      post_action_review_ids: arr(s.postActionReviewIds, 'text[]'),
      seeded_remedy_tier1_id: lit(s.seededRemedyTier1Id),
      seeded_remedy_tier2_id: lit(s.seededRemedyTier2Id),
    }))),

  upsert('reviews',
    ['id', 'restaurant_id', 'restaurant_menu_item_id', 'catalog_item_id', 'location_id',
     'rating', 'comment', 'price', 'date', 'food_category', 'phase', 'scenario_id',
     'categories', 'sentiment'],
    seed.reviews.map((r) => ({
      id: lit(r.id),
      restaurant_id: lit(r.restaurantId),
      restaurant_menu_item_id: lit(r.restaurantMenuItemId),
      catalog_item_id: lit(r.catalogItemId),
      location_id: lit(r.locationId),
      rating: r.rating,
      comment: lit(r.comment),
      price: r.price,
      date: lit(r.date),
      food_category: lit(r.foodCategory),
      phase: lit(r.phase),
      scenario_id: lit(r.scenarioId ?? null),
      categories: arr(r.tags?.categories ?? [], 'problem_category[]'),
      sentiment: lit(r.tags?.sentiment ?? 'Neutral'),
    }))),

  'commit;',
  '',
].join('\n');

await writeFile('supabase/seed.sql', sql);

console.log(
  `supabase/seed.sql — ${seed.locations.length} locations, ${seed.menuCatalog.length} catalog items, ` +
  `${remedies.length} remedies, ${seed.users.length} owners, ${seed.restaurants.length} restaurants, ` +
  `${seed.restaurantMenuItems.length} menu items, ${seed.scenarios.length} scenarios, ${seed.reviews.length} reviews`,
);
